version: "3.7"

services:
  deno:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: /bin/bash -c 'deno --allow-net /annict-dashboard/server.ts -p 9000'
    env_file:
      - .env.development
    ports:
      - 9000:9000
    volumes:
      - .:/annict-dashboard
